# Generated by Django 5.2.12 on 2026-04-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_order_payment_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settlement',
            old_name='commission_total',
            new_name='commission_amount',
        ),
        migrations.RenameField(
            model_name='settlement',
            old_name='producer_payment_total',
            new_name='net_payout',
        ),
        migrations.AddField(
            model_name='settlement',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Commission percentage (e.g., 5.00 for 5%)', max_digits=5),
            preserve_default=False,
        ),
    ]
